In [72]:
import numpy as np
import matplotlib.pyplot as plt

# Pincipal Components Analysis (without Sklearn)

In [67]:
# create a matrix A
A = np.random.rand(20,2)
A

array([[0.67070524, 0.07659979],
       [0.16565933, 0.25019565],
       [0.47534683, 0.42398635],
       [0.40896053, 0.71837452],
       [0.633326  , 0.36478681],
       [0.91977546, 0.16786683],
       [0.10434767, 0.23648041],
       [0.40732919, 0.70652894],
       [0.93670559, 0.62717748],
       [0.16393585, 0.13148286],
       [0.9064057 , 0.04783674],
       [0.51566573, 0.17415568],
       [0.49065471, 0.21229126],
       [0.9233331 , 0.42656813],
       [0.48877764, 0.9853701 ],
       [0.02815983, 0.55881624],
       [0.74261812, 0.06339286],
       [0.37604351, 0.92133609],
       [0.73649743, 0.07623449],
       [0.58651889, 0.5692749 ]])

## Step 1: Standardise the data

In [68]:
def standardise(matrix):
    for k in range(0,matrix.shape[1]):
        mean = sum([x[k] for x in matrix])/matrix.shape[0]
        std = np.sqrt(sum([(x[k]-mean)**2 for x in matrix])/(matrix.shape[0]-1))
        for i in range(0,matrix.shape[0]):
            matrix[i,k] = (matrix[i,k] - mean) / std
    return matrix

standard_A = standardise(A)
standard_A

array([[ 0.48729073, -1.06198448],
       [-1.31346829, -0.46793509],
       [-0.20926657,  0.12678105],
       [-0.44596926,  1.13418476],
       [ 0.35401375, -0.07580126],
       [ 1.37535938, -0.74966637],
       [-1.53207716, -0.51486898],
       [-0.45178587,  1.09364889],
       [ 1.43572436,  0.8221062 ],
       [-1.31961341, -0.87417325],
       [ 1.32768903, -1.16041237],
       [-0.06550811, -0.72814579],
       [-0.15468579, -0.59764488],
       [ 1.38804428,  0.13561595],
       [-0.16137856,  2.04785034],
       [-1.80372759,  0.5881723 ],
       [ 0.74369866, -1.10717893],
       [-0.56333605,  1.82872435],
       [ 0.72187511, -1.06323455],
       [ 0.18712135,  0.62396211]])

## Step 2: Construct covariance matrix

In [69]:
def covariance(x,y):
    x_mean = sum([xi for xi in x])/len(x)
    y_mean = sum([yi for yi in y])/len(y)
    N = len(x)-1
    return sum([(xi-x_mean)*(yi-y_mean) for (xi,yi) in zip(x,y)])/N

def covariance_matrix(matrix):
    C = np.zeros((matrix.shape[1],matrix.shape[1]))
    for k in range(0,matrix.shape[1]):
        for i in range(0,matrix.shape[1]):
            C[i,k] = covariance(matrix[:,i],matrix[:,k])
    return C

C = covariance_matrix(standard_A)
C

array([[ 1.        , -0.20908018],
       [-0.20908018,  1.        ]])

## Step 3: Compute the eigenvalues and eigenvectors of the covariance matrix

In [70]:
eig_vals, eig_vecs = np.linalg.eig(C)

print(eig_vals)
print(eig_vecs)

[0.79091982 1.20908018]
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


## Step 4: Recast the data across the principal component axes

In [75]:
PC = np.zeros((A.shape))
for i in range(eig_vecs.shape[0]):
    PC[:,i] = np.dot(np.transpose(eig_vecs[:,i]),np.transpose(standard_A))
PC

array([[ 0.40636985,  1.09550301],
       [ 1.25964241, -0.59788226],
       [ 0.05832607, -0.23762155],
       [-0.48664185, -1.11733763],
       [-0.19672594,  0.3039251 ],
       [-0.44243177,  1.50262012],
       [ 1.44740949, -0.7192748 ],
       [-0.4538657 , -1.0927874 ],
       [-1.5965273 ,  0.43389357],
       [ 1.55124142, -0.31497375],
       [-0.11828246,  1.75935338],
       [ 0.56119806,  0.46855559],
       [ 0.53197812,  0.31321938],
       [-1.07739048,  0.88560057],
       [-1.33393699, -1.56216073],
       [ 0.85952739, -1.69132864],
       [ 0.25701936,  1.3087681 ],
       [-0.89476465, -1.69144213],
       [ 0.24137758,  1.26226315],
       [-0.57352261, -0.30889307]])